config/routes.rb
Embertest::Application.routes.draw do

  get "test/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get "home/index"
  #website root
  root to: 'home#index'

namespace :api do
  namespace :v1 do
      resources :stories, only: :index
  end
end
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/story.rb
# app/models/story.rb

class Story < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/stories_controller.rb
class Api::V1::StoriesController < ApplicationController
  respond_to :json

  def index
    respond_with Story.all
  end

  private

  def story_params
    params.require(:story).permit(:name, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # for pretty alert messages using the flash command
   def bootstrap_class_for flash_type
    case flash_type
    when :success
    "alert-success"
    when :error
    "alert-danger"
    when :alert
    "alert-danger"
    when :notice
    "alert-info"
    when :warning
    "alert-warning"
    else
    flash_type.to_s
end
end
  
  #for devise login/signup form
    def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/home/index.html.erb
<div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Embertest</h1>
                        <h3>Playing with new gems and Ember.js</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                          <% if !user_signed_in? %>
                              <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#signin">
                                Sign in
                              </button>
                          <% else %>
                            <%= link_to "Test area", test_index_path, class: "btn btn-primary btn-lg" %>
                          <% end %>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

<script type="text/x-handlebars">
{{ outlet }}
</script>

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Death to the Stock Photo:
                        <br>Special Thanks</h2>
                    <p class="lead">A special thanks to Death to the Stock Photo for providing the photographs that you see in this template. <a target="_blank" href="http://join.deathtothestockphoto.com/">Visit their website</a> to become a member.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                  <%= image_tag "ipad.png", class: 'img-responsive' %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">3D Device Mockups
                        <br>by PSDCovers</h2>
                    <p class="lead">Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by PSDCovers! <a target="_blank" href="http://www.psdcovers.com/">Visit their website</a> to download some of their awesome, free photoshop actions!</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                  <%= image_tag "doge.png", class: 'img-responsive' %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Google Web Fonts and
                        <br>Font Awesome Icons</h2>
                    <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                  <%= image_tag "phones.png", class: 'img-responsive' %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Connect to CCNP-PRO:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                      <li><a href="http://twitter.com/ccnppro" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                      <li><a href="http://github.com/slacker87" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li><a href="http://lnkd.in/db2Acsr" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
<div class="col-md-12" style="margin-top: -70px;margin-bottom:10px;">
	  <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="margin-top:9px;margin-right:10px;">&times;</button>
		<div class="alert <%= bootstrap_class_for(type) %> fade in centered-text" align="center" style="width: 100%;">
 	 	<%= message %>
		</div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="#home">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; CCNP-PRO 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_modals.html.erb
<!--- sign_in modal -->
<!-- Modal -->
<div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="signinlLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'devise/sessions/new' %>
      </div>
    </div>
  </div>
</div>

<!-- sign_up modal -->
<!-- Modal -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="signupLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Sign up</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'devise/registrations/new' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <%= render partial: "layouts/navbar_signed_in" %>
<% else %>
  <%= render partial: "layouts/navbar_signed_out" %>
<% end %>

app/views/layouts/_navbar_signed_in.html.erb
<%= render partial: "layouts/modals" %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Embertest</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                  <%= current_user.email %>
                  <div class="dropdown btn btn-default" align="center" style="margin-top: 5px;">
                    <a data-toggle="dropdown" href="#" class="fa fa-bars nav-dropdown" style="text-decoration: none;"></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                      <li><%= link_to "Home", root_path %></li>
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>         
                    </ul>
                </div>
            <!-- /.navbar-collapse -->
            </ul>
          </div>
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_navbar_signed_out.html.erb
<%= render partial: "layouts/modals" %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Embertest</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                  <div class="dropdown btn btn-default" align="center" style="margin-top: 5px;">
                    <a data-toggle="dropdown" href="#" class="fa fa-bars nav-dropdown" style="text-decoration: none;"></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li><%= link_to "Home", root_path %></li>
                     <li><a data-toggle="modal" data-target="#signin">
                          Sign in
                     </a>
                      </li><li>
                      <a data-toggle="modal" data-target="#signup">
                         Sign up
                      </a>
                      </li>         
                  </ul>
            </div>
            <!-- /.navbar-collapse -->
            </ul>
          </div>
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Embertest</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <%= render partial: "layouts/navbar" %>
<%= render partial: "layouts/flash_messages", flash: flash %>
<%= yield %>
  <%= render partial: "layouts/footer" %>
</body>
</html>